config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  # HACK: Prevent devise sign_up routes for chefs/delivery_me
  [:chefs, :couriers].each do |user_type|
    match "/#{user_type}/sign_up", to: "pages#not_found", via: :all
  end

  # 1. Customers
  devise_for :customers
  authenticate :customer do
    resources :order_items, only: [:create, :update]
    scope :customers do
      get "/" => "customers/application#dashboard", as: :customers_dashboard
      get "example_protected_route" => "customers/application#example_protected_route"
    end
    namespace :customers do
      post "checkout" => "application#checkout"
      post "charge" => "application#charge"
      resources :orders, only: [:index, :edit, :update]
      resources :menu_item_feedbacks, only: [:update]
    end
  end

  # 2. Managers
  devise_for :managers
  authenticate :manager do
    scope :managers  do
      get "/" => "managers/application#dashboard", as: :managers_dashboard
      get "example_protected_route" => "managers/application#example_protected_route"
      resources :chefs do
        post "upvote" => "chefs#upvote", on: :collection
        post "downvote" => "chefs#downvote", on: :collection
      end
      resources :couriers
    end
    namespace :managers do
      resources :orders, only: [:show, :index, :update]
      resources :restaurants, only: [:edit, :update]
    end
  end

  # 3. Chefs
  devise_for :chefs
  authenticate :chef do
    scope :chefs do
      get "/" => "chefs/application#dashboard", as: :chefs_dashboard
      get "example_protected_route" => "chefs/application#example_protected_route"
      resources :menu_items
    end
  end

  # 4: Couriers (Delivery personnel)
  devise_for :couriers
  authenticate :courier do
    scope :couriers do
      get "/" => "couriers/application#dashboard", as: :couriers_dashboard
      get "example_protected_route" => "couriers/application#example_protected_route"
    end

    namespace :couriers do
      resources :orders, only: [:show, :update]
    end
  end

  # 5: All Users
  resources :restaurants, only: [:index, :show]

  # TOO MANY COOKS!
  get "/too_many_cooks" => "pages#too_many_cooks"

end

app/models/chef.rb
class Chef < User
  belongs_to :manager, class_name: "Manager", foreign_key: "manager_id", optional: true
  has_many :menu_items, dependent: :destroy
  delegate :restaurant, to: :manager
  enum status: { fired: -2, danger: -1, neutral: 0, good: 1, great: 2, excellent: 3 }

  PROMOTION_STEPS = Chef.statuses.keys.freeze

  def upvote
    return if excellent?
    vote amount: 1
  end

  def downvote
    return if fired?
    vote amount: -1
  end

  def reset_promotion_step!(status: :neutral, updown: 0)
    self.update status: status, updown: updown
  end

  private
  def reset_updown_if_necessary!
    self.update(updown: 0) if self.updown.abs >= 3
  end

  def promote_or_demote_if_necessary!
    curr_index = PROMOTION_STEPS.find_index(self.status)
    new_status = if self.updown >= 3 # PROMOTE
      PROMOTION_STEPS[curr_index + 1]
    elsif self.updown <= -3 # DEMOTE!
      PROMOTION_STEPS[curr_index - 1]
    end
    self.update status: new_status unless new_status.nil?
  end

  def vote(amount:)
    self.update updown: (self.updown + amount)
    promote_or_demote_if_necessary!
    reset_updown_if_necessary!
  end

end

app/controllers/chefs/application_controller.rb
module Chefs
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception

    def dashboard
      render "chefs/dashboard"
    end

    def example_protected_route
      render plain: "chefs/application_controller#example_protected_route is working"
    end

  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_manager!, only: [:upvote, :downvote]

  # GET /chefs
  def index
    @chefs = current_manager.chefs.all
  end

  # GET /chefs/1
  def show
  end

  # GET /chefs/new
  def new
    @chef = Chef.new
  end

  # GET /chefs/1/edit
  def edit
  end

  # POST /chefs
  def create
    @chef = current_manager.chefs.build(chef_params)
    @chef.manager = current_manager

    if @chef.save
      redirect_to @chef, notice: 'Chef was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /chefs/1
  def update
    if @chef.update(chef_params)
      redirect_to @chef, notice: 'Chef was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /chefs/1
  def destroy
    @chef.destroy
    redirect_to chefs_url, notice: 'Chef was successfully destroyed.'
  end

  def upvote
    chef = current_manager.chefs.find(params[:id])
    chef.upvote
    render json: {}, status: ok
  end

  def downvote
    chef = current_manager.chefs.find(params[:id])
    chef.downvote
    render json: {}, status: ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chef
      @chef = Chef.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def chef_params
      params.require(:chef).permit(:email, :name, :address, :password, :password_confirmation)
    end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/views/chefs/_form.html.erb
<%= form_with(model: chef, local: true) do |form| %>
  <% if chef.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chef.errors.count, "error") %> prohibited this chef from being saved:</h2>

      <ul>
      <% chef.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :chef_email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :chef_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :chef_address %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :chef_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :chef_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chefs/dashboard.html.erb
<h1>Chef Dashboard</h1>

<%= link_to "Edit Menu Items for: #{current_chef.restaurant.name}", menu_items_path %>
<br>

app/views/chefs/edit.html.erb
<h1>Editing Chef</h1>

<%= render 'form', chef: @chef %>

<%= link_to 'Show', @chef %> |
<%= link_to 'Back', chefs_path %>

app/views/chefs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chefs</h1>

<table>
  <thead>
    <tr>
      <th colspan="1">name</th>
      <th colspan="1">email</th>
      <th colspan="1">address</th>
    </tr>
  </thead>

  <tbody>
    <% @chefs.each do |chef| %>
      <tr>
        <td><%= chef.name %></td>
        <td><%= chef.email %></td>
        <td><%= chef.address %></td>
        <td><%= link_to 'Show', chef %></td>
        <td><%= link_to 'Edit', edit_chef_path(chef) %></td>
        <td><%= link_to 'Destroy', chef, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chef', new_chef_path %>

app/views/chefs/new.html.erb
<h1>New Chef</h1>

<%= render 'form', chef: @chef %>

<%= link_to 'Back', chefs_path %>

app/views/chefs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chef_path(@chef) %> |
<%= link_to 'Back', chefs_path %>