config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  # HACK: Prevent devise sign_up routes for chefs/delivery_me
  [:chefs, :couriers].each do |user_type|
    match "/#{user_type}/sign_up", to: "pages#not_found", via: :all
  end

  # 1. Customers
  devise_for :customers
  authenticate :customer do
    resources :order_items, only: [:create, :update]
    scope :customers do
      get "/" => "customers/application#dashboard", as: :customers_dashboard
      get "example_protected_route" => "customers/application#example_protected_route"
    end
    namespace :customers do
      post "checkout" => "application#checkout"
      post "charge" => "application#charge"
      resources :orders, only: [:index, :edit, :update]
      resources :menu_item_feedbacks, only: [:update]
    end
  end

  # 2. Managers
  devise_for :managers
  authenticate :manager do
    scope :managers  do
      get "/" => "managers/application#dashboard", as: :managers_dashboard
      get "example_protected_route" => "managers/application#example_protected_route"
      resources :chefs do
        post "upvote" => "chefs#upvote", on: :collection
        post "downvote" => "chefs#downvote", on: :collection
      end
      resources :couriers
    end
    namespace :managers do
      resources :orders, only: [:show, :index, :update]
      resources :restaurants, only: [:edit, :update]
    end
  end

  # 3. Chefs
  devise_for :chefs
  authenticate :chef do
    scope :chefs do
      get "/" => "chefs/application#dashboard", as: :chefs_dashboard
      get "example_protected_route" => "chefs/application#example_protected_route"
      resources :menu_items
    end
  end

  # 4: Couriers (Delivery personnel)
  devise_for :couriers
  authenticate :courier do
    scope :couriers do
      get "/" => "couriers/application#dashboard", as: :couriers_dashboard
      get "example_protected_route" => "couriers/application#example_protected_route"
    end

    namespace :couriers do
      resources :orders, only: [:show, :update]
    end
  end

  # 5: All Users
  resources :restaurants, only: [:index, :show]

  # TOO MANY COOKS!
  get "/too_many_cooks" => "pages#too_many_cooks"

end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  CENTS_IN_DOLLAR = 100

  belongs_to :restaurant
  belongs_to :chef, class_name: "Chef", foreign_key: "chef_id"

  validates_presence_of :name, :price_in_cents

  def price
    number_to_currency(price_in_cents / CENTS_IN_DOLLAR)
  end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_restaurant
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /menu_items
  def index
    @my_menu_items = current_chef.menu_items
    @other_menu_items = @restaurant.menu_items.where.not(chef: current_chef)
  end

  # GET /menu_items/1
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  def create
    @menu_item = current_chef.menu_items.build(menu_item_params)
    @menu_item.restaurant = @restaurant

    if @menu_item.save
      redirect_to @menu_item, notice: 'Menu item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /menu_items/1
  def update
    if @menu_item.update(menu_item_params)
      redirect_to @menu_item, notice: 'Menu item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /menu_items/1
  def destroy
    @menu_item.destroy
    redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = current_chef.manager.restaurant
    end

    def set_menu_item
      @menu_item = current_chef.menu_items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :price_in_cents)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item, local: true) do |form| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :menu_item_name %>
  </div>

  <div class="field">
    <%= form.label "Price in Cents" %>
    <%= form.text_field :price_in_cents, id: :menu_item_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>

app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h2>My Menu Items</h2>
<table>
  <thead>
    <tr>
      <th colspan="1">Name</th>
      <th colspan="1">Price</th>
      <th colspan="1">Created At</th>
      <th colspan="1">Updated At</th>
    </tr>
  </thead>

  <tbody>
    <% @my_menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.price %></td>
        <td><%= menu_item.created_at.stamp("April 21, 2017") %></td>
        <td><%= menu_item.updated_at.stamp("April 21, 2017") %></td>
        <td><%= link_to 'Show', menu_item %></td>
        <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
        <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Item', new_menu_item_path %>

<br>
<br>

<h2>Other Chef's Items</h2>
<table>
  <thead>
    <tr>
      <th colspan="1">Name</th>
      <th colspan="1">Price</th>
      <th colspan="1">Chef</th>
      <th colspan="1">Created At</th>
      <th colspan="1">Updated At</th>
    </tr>
  </thead>

  <tbody>
    <% @other_menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.price %></td>
        <td><%= menu_item.chef.name %></td>
        <td><%= menu_item.created_at.stamp("April 21, 2017") %></td>
        <td><%= menu_item.updated_at.stamp("April 21, 2017") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Back', menu_items_path %>

app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<h4>Name: <%= @menu_item.name %></h4>
<h4>Price: <%= @menu_item.price %></h4>

<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<%= link_to 'Back', menu_items_path %>