config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  # HACK: Prevent devise sign_up routes for chefs/delivery_me
  [:chefs, :couriers].each do |user_type|
    match "/#{user_type}/sign_up", to: "pages#not_found", via: :all
  end

  # 1. Customers
  devise_for :customers
  authenticate :customer do
    resources :order_items, only: [:create, :update]
    scope :customers do
      get "/" => "customers/application#dashboard", as: :customers_dashboard
      get "example_protected_route" => "customers/application#example_protected_route"
    end
    namespace :customers do
      post "checkout" => "application#checkout"
      post "charge" => "application#charge"
      resources :orders, only: [:index, :edit, :update]
      resources :menu_item_feedbacks, only: [:update]
    end
  end

  # 2. Managers
  devise_for :managers
  authenticate :manager do
    scope :managers  do
      get "/" => "managers/application#dashboard", as: :managers_dashboard
      get "example_protected_route" => "managers/application#example_protected_route"
      resources :chefs do
        post "upvote" => "chefs#upvote", on: :collection
        post "downvote" => "chefs#downvote", on: :collection
      end
      resources :couriers
    end
    namespace :managers do
      resources :orders, only: [:show, :index, :update]
      resources :restaurants, only: [:edit, :update]
    end
  end

  # 3. Chefs
  devise_for :chefs
  authenticate :chef do
    scope :chefs do
      get "/" => "chefs/application#dashboard", as: :chefs_dashboard
      get "example_protected_route" => "chefs/application#example_protected_route"
      resources :menu_items
    end
  end

  # 4: Couriers (Delivery personnel)
  devise_for :couriers
  authenticate :courier do
    scope :couriers do
      get "/" => "couriers/application#dashboard", as: :couriers_dashboard
      get "example_protected_route" => "couriers/application#example_protected_route"
    end

    namespace :couriers do
      resources :orders, only: [:show, :update]
    end
  end

  # 5: All Users
  resources :restaurants, only: [:index, :show]

  # TOO MANY COOKS!
  get "/too_many_cooks" => "pages#too_many_cooks"

end

app/models/courier.rb
class Courier < User
  belongs_to :manager, class_name: "Manager", foreign_key: "manager_id", optional: true
  delegate :restaurant, to: :manager
end

app/controllers/couriers/application_controller.rb
module Couriers
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception

    def dashboard
      @approved_orders = current_courier.restaurant.orders.approved
      @delivered_orders = current_courier.restaurant.orders.delivered
      render "couriers/dashboard"
    end


    def example_protected_route
      render plain: "couriers/application_controller#example_protected_route is working"
    end

  end
end

app/controllers/couriers/orders_controller.rb
module Couriers
  class OrdersController < ApplicationController

    before_action :set_order

    def show
    end

    def update
      if @order.update(order_params)
        redirect_to couriers_dashboard_path, notice: "Order status updated!"
      else
        redirect_to couriers_dashboard_path, notice: "Order update failed."
      end
    end

    private
    def order_params
      params.require(:order).permit(:status)
    end

    def set_order
      @order = current_courier.restaurant.orders.find(params[:id])
    end

  end
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  before_action :set_courier, only: [:show, :edit, :update, :destroy]

  # GET /couriers
  def index
    @couriers = current_manager.couriers.all
  end

  # GET /couriers/1
  def show
  end

  # GET /couriers/new
  def new
    @courier = Courier.new
  end

  # GET /couriers/1/edit
  def edit
  end

  # POST /couriers
  def create
    @courier = current_manager.couriers.build(courier_params)
    @courier.manager = current_manager

    if @courier.save
      redirect_to @courier, notice: 'Courier was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /couriers/1
  def update
    if @courier.update(courier_params)
      redirect_to @courier, notice: 'Courier was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /couriers/1
  def destroy
    @courier.destroy
    redirect_to couriers_url, notice: 'Courier was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_courier
      @courier = Courier.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def courier_params
      params.require(:courier).permit(:email, :name, :address, :password, :password_confirmation)
    end
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/views/couriers/_form.html.erb
<%= form_with(model: courier, local: true) do |form| %>
  <% if courier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(courier.errors.count, "error") %> prohibited this courier from being saved:</h2>

      <ul>
      <% courier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :courier_email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :courier_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :courier_address %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :courier_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :courier_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/couriers/_orders.html.erb
<% orders.each do |o| %>
  <div class="courier-order-panel">
    <div class="order">
      <div class="col customer-id">
        <b>Customer E-mail:</b>
        <span><%= o.customer.email %></span>
      </div>

      <div class="col customer-address">
        <b>Destination:</b>
        <span><%= o.customer.address %></span>
      </div>
    </div>

    <div class="update-status-form">
      <%= form_with(model: [:couriers, o], method: "PUT", local: true) do |form| %>
        <div class="field">
          <%= form.label :status %>

          <%= form.radio_button :status, :approved %>
          <%= form.label :status, :approved, style: "display: inline-block" %>
          <br />

          <%= form.radio_button :status, :delivered %>
          <%= form.label :status, :delivered, style: "display: inline-block" %>
          <br />
        </div>

        <div class="actions">
          <%= form.submit "Update Status" %>
          <%= link_to "Show Order", [:couriers, o], class: "" %>
        </div>
      <% end %>
    </div>
  </div>

<% end %>

app/views/couriers/dashboard.html.erb
<h1>Courier Dashboard</h1>


<h2>Approved Orders</h2>
<%= render partial: "couriers/orders", locals: { orders: @approved_orders } %>

<br/>
<br/>

<h2>Delivered Orders</h2>
<%= render partial: "couriers/orders", locals: { orders: @delivered_orders } %>

app/views/couriers/edit.html.erb
<h1>Editing Courier</h1>

<%= render 'form', courier: @courier %>

<%= link_to 'Show', @courier %> |
<%= link_to 'Back', couriers_path %>

app/views/couriers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Couriers</h1>

<table>
  <thead>
    <tr>
      <th colspan="1">name</th>
      <th colspan="1">email</th>
      <th colspan="1">address</th>
    </tr>
  </thead>

  <tbody>
    <% @couriers.each do |courier| %>
      <tr>
        <td><%= courier.name %></td>
        <td><%= courier.email %></td>
        <td><%= courier.address %></td>
        <td><%= link_to 'Show', courier %></td>
        <td><%= link_to 'Edit', edit_courier_path(courier) %></td>
        <td><%= link_to 'Destroy', courier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Courier', new_courier_path %>

app/views/couriers/new.html.erb
<h1>New Courier</h1>

<%= render 'form', courier: @courier %>

<%= link_to 'Back', couriers_path %>

app/views/couriers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_courier_path(@courier) %> |
<%= link_to 'Back', couriers_path %>