config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  # HACK: Prevent devise sign_up routes for chefs/delivery_me
  [:chefs, :couriers].each do |user_type|
    match "/#{user_type}/sign_up", to: "pages#not_found", via: :all
  end

  # 1. Customers
  devise_for :customers
  authenticate :customer do
    resources :order_items, only: [:create, :update]
    scope :customers do
      get "/" => "customers/application#dashboard", as: :customers_dashboard
      get "example_protected_route" => "customers/application#example_protected_route"
    end
    namespace :customers do
      post "checkout" => "application#checkout"
      post "charge" => "application#charge"
      resources :orders, only: [:index, :edit, :update]
      resources :menu_item_feedbacks, only: [:update]
    end
  end

  # 2. Managers
  devise_for :managers
  authenticate :manager do
    scope :managers  do
      get "/" => "managers/application#dashboard", as: :managers_dashboard
      get "example_protected_route" => "managers/application#example_protected_route"
      resources :chefs do
        post "upvote" => "chefs#upvote", on: :collection
        post "downvote" => "chefs#downvote", on: :collection
      end
      resources :couriers
    end
    namespace :managers do
      resources :orders, only: [:show, :index, :update]
      resources :restaurants, only: [:edit, :update]
    end
  end

  # 3. Chefs
  devise_for :chefs
  authenticate :chef do
    scope :chefs do
      get "/" => "chefs/application#dashboard", as: :chefs_dashboard
      get "example_protected_route" => "chefs/application#example_protected_route"
      resources :menu_items
    end
  end

  # 4: Couriers (Delivery personnel)
  devise_for :couriers
  authenticate :courier do
    scope :couriers do
      get "/" => "couriers/application#dashboard", as: :couriers_dashboard
      get "example_protected_route" => "couriers/application#example_protected_route"
    end

    namespace :couriers do
      resources :orders, only: [:show, :update]
    end
  end

  # 5: All Users
  resources :restaurants, only: [:index, :show]

  # TOO MANY COOKS!
  get "/too_many_cooks" => "pages#too_many_cooks"

end

app/models/manager.rb
class Manager < User
  has_one :restaurant, dependent: :destroy
  has_many :chefs, class_name: "Chef", dependent: :destroy
  has_many :couriers, class_name: "Courier", dependent: :destroy

  after_create :create_blank_restaurant

  private
    def create_blank_restaurant
      restaurant = Restaurant.new manager: self
      restaurant.save(validate: false)
    end
end

app/models/order.rb
class Order < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  enum status: [:started, :pending, :approved, :delivered, :feedback_approved, :feedback_rejected]

  has_many :order_items, dependent: :destroy
  has_many :menu_item_feedbacks
  belongs_to :customer, class_name: "Customer", foreign_key: "customer_id"
  belongs_to :restaurant

  default_scope             -> { order(updated_at: :desc) }
  scope :feedback_reviewed, -> { where(status: [:feedback_approved, :feedback_rejected]) }

  CENTS_IN_DOLLAR = 100

  def total_price_in_cents
    order_items.sum { |oi| oi.menu_item.price_in_cents * oi.quantity }
  end

  def total_price
    number_to_currency(total_price_in_cents / CENTS_IN_DOLLAR)
  end

  def add_item!(order_item_params)
    # If order_item is already in the cart, just increment the quantity
    if(order_item=self.order_items.find_by menu_item_id: order_item_params[:menu_item_id]).present?
      order_item.update(quantity: (order_item.quantity + order_item_params[:quantity].to_i))
    else
      self.order_items.build(order_item_params)
    end

    self.save!
  end

  def place_order
    new_balance = self.customer.balance_in_cents - self.total_price_in_cents
    return false if order_items.count == 0 || new_balance < 0
    self.customer.balance_in_cents = new_balance
    self.customer.save
    self.pending!

    self.order_items.each do |order_item|
      mif = MenuItemFeedback.new({
        customer: self.customer,
        order: self,
        menu_item: order_item.menu_item
      })
      mif.save(validate: false)
    end

    self.save
  end

end

app/controllers/couriers/orders_controller.rb
module Couriers
  class OrdersController < ApplicationController

    before_action :set_order

    def show
    end

    def update
      if @order.update(order_params)
        redirect_to couriers_dashboard_path, notice: "Order status updated!"
      else
        redirect_to couriers_dashboard_path, notice: "Order update failed."
      end
    end

    private
    def order_params
      params.require(:order).permit(:status)
    end

    def set_order
      @order = current_courier.restaurant.orders.find(params[:id])
    end

  end
end

app/controllers/customers/orders_controller.rb
module Customers
  class OrdersController < ApplicationController

    def index
      @orders = current_customer.orders.delivered
    end

    def edit
      @order = Order.find(params[:id])
    end

    def update
      @order = Order.find(params[:id])
      if @order.update(order_params)
        redirect_to edit_customers_order_path(@order), notice: "Feedback sent!"
      else
        redirect_to edit_customers_order_path(@order), notice: "Error!"
      end
    end

    private
    def order_params
      params.require(:order).permit(:comment)
    end

  end
end

app/controllers/managers/application_controller.rb
module Managers
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception

    def dashboard
      render "managers/dashboard"
    end

    def example_protected_route
      render plain: "managers/application_controller#example_protected_route is working"
    end

  end
end

app/controllers/managers/orders_controller.rb
module Managers
  class OrdersController < ApplicationController
    def show
      @order = current_manager.restaurant.orders.find(params[:id])
    end

    def index
      @orders_to_review = current_manager.restaurant.orders.where(status: :delivered)
      @orders_already_reviewed = current_manager.restaurant.orders.feedback_reviewed
      @other_orders = current_manager.restaurant.orders.where(status: [:pending, :approved])
    end

    def update
      order = current_manager.restaurant.orders.find(params[:id])
      if order.update(order_params)
        redirect_to managers_orders_path, notice: "Order status updated!"
      else
        redirect_to managers_orders_path, notice: "Order update failed."
      end
    end

    private

    def order_params
      params.require(:order).permit(:status)
    end

  end
end

app/controllers/managers/restaurants_controller.rb
module Managers
  class RestaurantsController < ApplicationController
    before_action :set_restaurant

    # GET /restaurants (it only displays the mangers ONE restauarnt)
    def index
    end

    # GET /restaurants/1/edit
    def edit
    end

    # PATCH/PUT /restaurants/1
    def update
      if @restaurant.update(restaurant_params)
        redirect_to edit_managers_restaurant_path(@restaurant), notice: 'Restaurant was successfully updated.'
      else
        render :edit
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_restaurant
        @restaurant = current_manager.restaurant
      end

      def restaurant_params
        params.require(:restaurant).permit(:name, :address)
      end
  end
end

app/views/managers/orders/_order.html.erb
<% hide_form ||= false %>

<div class="manager-order-panel">
  <div class="order">
    <div class="col order-id">
      <b>Order ID:</b>
      <span><%= order.id %></span>
    </div>

    <div class="col customer-id">
      <b>Customer E-mail:</b>
      <span><%= order.customer.email %></span>
    </div>

    <div class="col customer-address">
      <b>Destination:</b>
      <span><%= order.customer.address %></span>
    </div>
  </div>

  <div class="update-status-form">
    <% if hide_form %>
      <p><b>Feedback</b>: <%= order.feedback_approved? ? "Approved" : "Rejected" %></p>
    <% else %>
      <%= form_with(model: [:managers, order], method: "PUT", local: true) do |form| %>
        <div class="field">
          <%= form.label :status %>

          <%= form.radio_button :status, :pending %>
          <%= form.label :status, :pending, style: "display: inline-block" %>
          <br />

          <%= form.radio_button :status, :approved %>
          <%= form.label :status, :approved, style: "display: inline-block" %>
          <br />

          <%= form.radio_button :status, :delivered %>
          <%= form.label :status, :delivered, style: "display: inline-block" %>
          <br />

          <div class="actions">
            <%= form.submit "Update Status" %>
          </div>
        </div>
      <% end %>
      <%= link_to "Review Order", managers_order_path(order) %>
    <% end %>
  </div>
</div>

app/views/managers/orders/index.html.erb
<p id="notice"><%= notice %></p>

<ul>
  <li><a href="#orders-to-review">Orders To Review</a></li>
  <li><a href="#orders-already-reviewed">Orders Already Reviewed</a></li>
  <li><a href="#other-orders">Other Orders</a></li>
</ul>

<h2>Orders To Review for Feedback:</h2>
<div id="orders-to-review">
  <% @orders_to_review.each do |order| %>
    <%= render order %>
  <% end %>
  <br>
  <br>
</div>

<div id="orders-already-reviewed">
  <h2>Orders Already Reviewed</h2>
  <% @orders_already_reviewed.each do |order| %>
    <%= render order, hide_form: true %>
  <% end %>
  <br>
  <br>
</div>

<div id="other-orders">
  <h2>Other Orders</h2>
  <% @other_orders.each do |order| %>
    <%= render order %>
  <% end %>
  <br>
  <br>
</div>

app/views/managers/orders/show.html.erb
<h2>Customer</h2>
<h5>Name: <%= @order.customer.name %></h5>

<h2>Order Summary</h2>
<h5></h5>

<table>
  <thead>
    <tr>
      <th colspan="1">Item</th>
      <th colspan="1">Rating</th>
      <th colspan="1">Comment</th>
      <th colspan="1">Chef</th>
      <th colspan="1">Chef Status</th>
      <th colspan="1">Upvote Chef</th>
      <th colspan="1">Downvote Chef</th>
    </tr>
  </thead>

  <tbody>
    <% @order.menu_item_feedbacks.each do |mif| %>
      <tr class="managers-menu-item-feedbacks">
        <% chef = mif.menu_item.chef %>
        <td><%= mif.menu_item.name %></td>
        <td><%= mif.rating %></td>
        <td><%= mif.comment %></td>
        <td>
          <%= link_to chef.name, edit_chef_path(chef) %>
        </td>
        <td><%= chef.status %></td>
        <td style="text-align: center;">
          <% if chef.fired? %>
            <span>(Already Fired)</span>
          <% elsif chef.excellent? %>
            <span>(Already At Max)</span>
          <% else %>
            <a class="managers-upvote-chef" data-chef-id="<%= chef.id %>">
              <i class="fa fa-thumbs-up" aria-hidden="true"></i>
            </a>
          <% end %>
        </td>
        <td style="text-align: center;" >
          <% if chef.fired? %>
            <span>(Already Fired)</span>
          <% else %>
            <a class="managers-downvote-chef" data-chef-id="<%= chef.id %>">
              <i class="fa fa-thumbs-down" aria-hidden="true"></i>
            </a>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>